{
 "title": "Corporation Fat Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "corp",
    "label": "Corporation",
    "query": "SELECT\n  corporation_id as __value, corporation_name as __text\nFROM eveonline_evecorporationinfo\nWHERE alliance_id = 1\norder by corporation_name"
   },
   { "name": "fats_min", "label": "Low Fat Cutoff", "query": "5" },
   {
    "name": "mains",
    "query": "SELECT \n  count(distinct T7.`character_name`)\nFROM \n  `eveonline_evecharacter` \n  LEFT OUTER JOIN `authentication_characterownership` ON (\n    `eveonline_evecharacter`.`id` = `authentication_characterownership`.`character_id`\n  ) \n  LEFT OUTER JOIN `auth_user` ON (\n    `authentication_characterownership`.`user_id` = `auth_user`.`id`\n  ) \n  LEFT OUTER JOIN `authentication_userprofile` ON (\n    `auth_user`.`id` = `authentication_userprofile`.`user_id`\n  ) \n  LEFT OUTER JOIN `eveonline_evecharacter` T7 ON (\n    `authentication_userprofile`.`main_character_id` = T7.`id`\n  ) \nWhere \n  T7.`corporation_id` in ($corp) "
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  from_unixtime($__from/1000, '%Y %M %D') AS \"Start\",\n  from_unixtime($__to/1000, '%Y %M %D') AS \"End\"\nFROM aadiscordbot_authbotconfiguration\n"
    }
   ]
  },
  {
   "title": "Mains With Low Fats",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  concat(count(distinct T7.`character_name`),\" / \",$mains)\nFROM \n  `eveonline_evecharacter` \n  LEFT OUTER JOIN `authentication_characterownership` ON (\n    `eveonline_evecharacter`.`id` = `authentication_characterownership`.`character_id`\n  ) \n  LEFT OUTER JOIN `auth_user` ON (\n    `authentication_characterownership`.`user_id` = `auth_user`.`id`\n  ) \n  LEFT OUTER JOIN `authentication_userprofile` ON (\n    `auth_user`.`id` = `authentication_userprofile`.`user_id`\n  ) \n  LEFT OUTER JOIN `eveonline_evecharacter` T7 ON (\n    `authentication_userprofile`.`main_character_id` = T7.`id`\n  ) \nWhere \n  T7.`corporation_id` in ($corp) \n  and T7.`character_name` not in (\n    SELECT \n      T7.`character_name` \n    FROM \n      `afat_afat` \n      INNER JOIN `afat_afatlink` ON (\n        `afat_afat`.`afatlink_id` = `afat_afatlink`.`id`\n      ) \n      INNER JOIN `eveonline_evecharacter` ON (\n        `afat_afat`.`character_id` = `eveonline_evecharacter`.`id`\n      ) \n      LEFT OUTER JOIN `authentication_characterownership` ON (\n        `eveonline_evecharacter`.`id` = `authentication_characterownership`.`character_id`\n      ) \n      LEFT OUTER JOIN `auth_user` ON (\n        `authentication_characterownership`.`user_id` = `auth_user`.`id`\n      ) \n      LEFT OUTER JOIN `authentication_userprofile` ON (\n        `auth_user`.`id` = `authentication_userprofile`.`user_id`\n      ) \n      LEFT OUTER JOIN `eveonline_evecharacter` T7 ON (\n        `authentication_userprofile`.`main_character_id` = T7.`id`\n      ) \n    WHERE \n      $__timeFilter(`afat_afatlink`.`afattime`) \n      and T7.`corporation_id` in ($corp) \n    GROUP BY \n      T7.`character_name` \n    HAVING \n      count(`afat_afat`.`id`) > $fats_min\n  ) \n"
    }
   ]
  },
  {
   "title": "Total Fats",
   "type": "table",
   "gridPos": { "h": 21, "w": 8, "x": 11, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \nT7.`character_name` as \"Character\",\ncount(`afat_afat`.`id`) as \"Fats\"\nFROM `afat_afat`\nINNER JOIN `afat_afatlink` ON (`afat_afat`.`afatlink_id` = `afat_afatlink`.`id`) \nINNER JOIN `eveonline_evecharacter` ON (`afat_afat`.`character_id` = `eveonline_evecharacter`.`id`) \nLEFT OUTER JOIN `authentication_characterownership` ON (`eveonline_evecharacter`.`id` = `authentication_characterownership`.`character_id`) \nLEFT OUTER JOIN `auth_user` ON (`authentication_characterownership`.`user_id` = `auth_user`.`id`) \nLEFT OUTER JOIN `authentication_userprofile` ON (`auth_user`.`id` = `authentication_userprofile`.`user_id`) \nLEFT OUTER JOIN `eveonline_evecharacter` T7 ON (`authentication_userprofile`.`main_character_id` = T7.`id`) \nWHERE $__timeFilter(`afat_afatlink`.`afattime`) and T7.`corporation_id` in ($corp)\nGROUP BY T7.`character_name`\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 2 },
   "options": {
    "content": "<div style=\"display: flex;justify-content: center;\">\r\n  <img\r\n    data-src=\"https://images.evetech.net/corporations/$corp/logo\"\r\n    width=\"256\"\r\n    height=\"256\"\r\n    src=\"https://images.evetech.net/corporations/$corp/logo\"\r\n  />\r\n</div>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  last_kill AS \"time\",\n  id\nFROM aastatistics_statscharacter\nWHERE\n  $__timeFilter(last_kill)\nORDER BY last_kill"
    }
   ]
  },
  {
   "title": "Member Fats",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \n$__timeGroupAlias(`afat_afatlink`.`afattime`,1d,0),\nT7.`character_name` as metric,\ncount(`afat_afat`.`id`) as \"Fats\"\nFROM `afat_afat`\nINNER JOIN `afat_afatlink` ON (`afat_afat`.`afatlink_id` = `afat_afatlink`.`id`) \nINNER JOIN `eveonline_evecharacter` ON (`afat_afat`.`character_id` = `eveonline_evecharacter`.`id`) \nLEFT OUTER JOIN `authentication_characterownership` ON (`eveonline_evecharacter`.`id` = `authentication_characterownership`.`character_id`) \nLEFT OUTER JOIN `auth_user` ON (`authentication_characterownership`.`user_id` = `auth_user`.`id`) \nLEFT OUTER JOIN `authentication_userprofile` ON (`auth_user`.`id` = `authentication_userprofile`.`user_id`) \nLEFT OUTER JOIN `eveonline_evecharacter` T7 ON (`authentication_userprofile`.`main_character_id` = T7.`id`) \nWHERE $__timeFilter(`afat_afatlink`.`afattime`) and T7.`corporation_id` in ($corp)\nGROUP BY T7.`character_name`, $__timeGroup(`afat_afatlink`.`afattime`,1d,0)\norder by 1"
    }
   ]
  },
  {
   "title": "Mains with less than $fats_min Fats",
   "type": "table",
   "gridPos": { "h": 36, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  distinct T7.`character_name` as \"Main\"\nFROM \n  `eveonline_evecharacter` \n  LEFT OUTER JOIN `authentication_characterownership` ON (\n    `eveonline_evecharacter`.`id` = `authentication_characterownership`.`character_id`\n  ) \n  LEFT OUTER JOIN `auth_user` ON (\n    `authentication_characterownership`.`user_id` = `auth_user`.`id`\n  ) \n  LEFT OUTER JOIN `authentication_userprofile` ON (\n    `auth_user`.`id` = `authentication_userprofile`.`user_id`\n  ) \n  LEFT OUTER JOIN `eveonline_evecharacter` T7 ON (\n    `authentication_userprofile`.`main_character_id` = T7.`id`\n  ) \nWhere \n  T7.`corporation_id` in ($corp) \n  and T7.`character_name` not in (\n    SELECT \n      T7.`character_name` \n    FROM \n      `afat_afat` \n      INNER JOIN `afat_afatlink` ON (\n        `afat_afat`.`afatlink_id` = `afat_afatlink`.`id`\n      ) \n      INNER JOIN `eveonline_evecharacter` ON (\n        `afat_afat`.`character_id` = `eveonline_evecharacter`.`id`\n      ) \n      LEFT OUTER JOIN `authentication_characterownership` ON (\n        `eveonline_evecharacter`.`id` = `authentication_characterownership`.`character_id`\n      ) \n      LEFT OUTER JOIN `auth_user` ON (\n        `authentication_characterownership`.`user_id` = `auth_user`.`id`\n      ) \n      LEFT OUTER JOIN `authentication_userprofile` ON (\n        `auth_user`.`id` = `authentication_userprofile`.`user_id`\n      ) \n      LEFT OUTER JOIN `eveonline_evecharacter` T7 ON (\n        `authentication_userprofile`.`main_character_id` = T7.`id`\n      ) \n    WHERE \n      $__timeFilter(`afat_afatlink`.`afattime`) \n      and T7.`corporation_id` in ($corp) \n    GROUP BY \n      T7.`character_name` \n    HAVING \n      count(`afat_afat`.`id`) > $fats_min\n  ) \n"
    }
   ]
  },
  {
   "title": "Ghost Fats",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT \n$__timeGroupAlias(`afat_afatlink`.`afattime`,1d,0),\nT7.`character_name` as metric,\ncount(`afat_afat`.`id`) as \"Fats\"\nFROM `afat_afat`\nINNER JOIN `afat_afatlink` ON (`afat_afat`.`afatlink_id` = `afat_afatlink`.`id`) \nINNER JOIN `eveonline_evecharacter` ON (`afat_afat`.`character_id` = `eveonline_evecharacter`.`id`) \nLEFT OUTER JOIN `authentication_characterownership` ON (`eveonline_evecharacter`.`id` = `authentication_characterownership`.`character_id`) \nLEFT OUTER JOIN `auth_user` ON (`authentication_characterownership`.`user_id` = `auth_user`.`id`) \nLEFT OUTER JOIN `authentication_userprofile` ON (`auth_user`.`id` = `authentication_userprofile`.`user_id`) \nLEFT OUTER JOIN `eveonline_evecharacter` T7 ON (`authentication_userprofile`.`main_character_id` = T7.`id`) \nWHERE $__timeFilter(`afat_afatlink`.`afattime`) and T7.`corporation_id` in ($corp) and `eveonline_evecharacter`.`corporation_id` = 98534707\nGROUP BY T7.`character_name`, $__timeGroup(`afat_afatlink`.`afattime`,1d,0)\norder by 1"
    }
   ]
  },
  {
   "title": "Total Ghost Fats",
   "type": "table",
   "gridPos": { "h": 22, "w": 8, "x": 11, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT \nT7.`character_name` as \"Character\",\nMAX(`eveonline_evecharacter`.`character_name`) as \"Ghost\",\ncount(`afat_afat`.`id`) as \"Fats\"\nFROM `afat_afat`\nINNER JOIN `afat_afatlink` ON (`afat_afat`.`afatlink_id` = `afat_afatlink`.`id`) \nINNER JOIN `eveonline_evecharacter` ON (`afat_afat`.`character_id` = `eveonline_evecharacter`.`id`) \nLEFT OUTER JOIN `authentication_characterownership` ON (`eveonline_evecharacter`.`id` = `authentication_characterownership`.`character_id`) \nLEFT OUTER JOIN `auth_user` ON (`authentication_characterownership`.`user_id` = `auth_user`.`id`) \nLEFT OUTER JOIN `authentication_userprofile` ON (`auth_user`.`id` = `authentication_userprofile`.`user_id`) \nLEFT OUTER JOIN `eveonline_evecharacter` T7 ON (`authentication_userprofile`.`main_character_id` = T7.`id`) \nWHERE $__timeFilter(`afat_afatlink`.`afattime`) and T7.`corporation_id` in ($corp) and `eveonline_evecharacter`.`corporation_id` = 98534707\nGROUP BY T7.`character_name`\n"
    }
   ]
  }
 ]
}