{
 "title": "Wallet Experiments",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "corporation_id",
    "query": "select cinfo.corporation_name as __text, cinfo.corporation_id as __value from corptools_corporationaudit caudit\njoin eveonline_evecorporationinfo cinfo on cinfo.id = caudit.corporation_id;"
   },
   {
    "name": "division",
    "query": "select cwd.id as __value from corptools_corporationwalletdivision cwd\njoin corptools_corporationaudit caudit on caudit.corporation_id = cwd.corporation_id\njoin eveonline_evecorporationinfo cinfo on cinfo.id = caudit.corporation_id\nwhere cinfo.corporation_id in ($corporation_id);"
   },
   {
    "name": "ref_type",
    "query": "select\n    distinct(cw.ref_type)\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $corporation_id;"
   }
  ]
 },
 "panels": [
  {
   "title": "Wallet Balance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select\n    cw.balance, \n    cw.date as time\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $corporation_id and cw.amount>0\norder BY $__timeGroup(cw.date,'1m')"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n    (cw.amount) as amtIn, \n    cw.date as time\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $corporation_id and cw.amount>0\norder BY $__timeGroup(cw.date,'1m')"
    },
    {
     "rawSql": "select\n    (cw.amount) as amtOut, \n    cw.date as time\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $corporation_id and cw.amount<0\norder BY $__timeGroup(cw.date,'1m')"
    }
   ]
  },
  {
   "title": "Wallet Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n    cw.balance, \n    cw.date as time\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $corporation_id and cw.amount>0\norder BY $__timeGroup(cw.date,'1m')"
    }
   ]
  },
  {
   "title": "Ratting Ticks",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n    (cw.amount * 100 / 7.5) as tick, \n    cw.date as time\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $corporation_id and cw.ref_type = 'bounty_prizes'\n-- order BY $__timeGroup(cw.date,'1s')"
    }
   ]
  },
  {
   "title": "Wallet - Raw",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select\n    cw.amount, cw.balance, cw.date, cw.description, cw.reason, cw.ref_type\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $corporation_id and cw.ref_type in ($ref_type);"
    }
   ]
  }
 ]
}