{
 "title": "Krabbing Income - WIP",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Corporation",
    "query": "select cinfo.corporation_name as __text, cinfo.corporation_id as __value from corptools_corporationaudit caudit\njoin eveonline_evecorporationinfo cinfo on cinfo.id = caudit.corporation_id;"
   },
   {
    "name": "RefType",
    "label": "Reference Type",
    "query": "select\n    distinct(cw.ref_type)\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $Corporation;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Income Refrence Type",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    SUM(amount) AS \"Amount\"\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cinfo.corporation_id = $Corporation and cw.ref_type in ($RefType)\nand\n  $__timeFilter(cw.date);"
    }
   ]
  },
  {
   "title": "Total Tax Income",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n    sum(cw.amount), cinfo.corporation_id\nfrom\n    corptools_corporationwalletjournalentry cw\njoin corptools_corporationwalletdivision cwd on cw.division_id = cwd.id\njoin corptools_corporationaudit caudit on cwd.corporation_id = caudit.id\njoin eveonline_evecorporationinfo cinfo on caudit.corporation_id = cinfo.id\nwhere cw.ref_type in ($RefType) and  $__timeFilter(cw.date)\ngroup by cinfo.corporation_id"
    }
   ]
  },
  {
   "title": "Krab Income Player by Corp - Current Month",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\ncorporation_name as \"Corporation\",  sum(amount) as \"ISK\"\nFROM \n  corptools_characterwalletjournalentry as wallet\nINNER JOIN eveonline_evecharacter on eveonline_evecharacter.character_id=second_party_id\nWHERE (ref_type = \"bounty_prizes\" OR ref_type='ess_escrow_transfer' OR ref_type='corporate_reward_payout' OR ref_type='agent_reward_missions')\nAND MONTH(date) = MONTH(CURRENT_TIMESTAMP)\ngroup by corporation_name, Month(date);\n\n"
    }
   ]
  },
  {
   "title": "Player Krab Income - Current Month",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT character_name as \"Krabber\", corporation_name as \"Corporation\", sum(amount) as \"Amount\"\nFROM \n  corptools_characterwalletjournalentry\nINNER JOIN eveonline_evecharacter on eveonline_evecharacter.character_id=second_party_id\nWHERE (ref_type = \"bounty_prizes\" OR ref_type='ess_escrow_transfer' OR ref_type='corporate_reward_payout' OR ref_type='agent_reward_missions') AND MONTH(date) = MONTH(CURRENT_TIMESTAMP)\ngroup by second_party_id, Month(date);"
    }
   ]
  },
  {
   "title": "Corp Tax Income (Rewards) - Current Month",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\ncorporation_name as \"Corporation\", SUM(amount) AS \"Amount\"\nFROM \n  corptools_corporationwalletjournalentry as wallet\nINNER JOIN eveonline_evecharacter on eveonline_evecharacter.character_id=second_party_id\nWHERE \n  ref_type = \"corporate_reward_payout\" AND MONTH(date) = MONTH(CURRENT_TIMESTAMP)\ngroup by corporation_name, Month(date);"
    }
   ]
  },
  {
   "title": "Corp Tax Income (Missions) - Current Month",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\ncorporation_name as \"Corporation\", SUM(amount) AS \"Amount\"\nFROM \n  corptools_corporationwalletjournalentry as wallet\nINNER JOIN eveonline_evecharacter on eveonline_evecharacter.character_id=second_party_id\nWHERE \n  ref_type = \"agent_mission_reward\" AND MONTH(date) = MONTH(CURRENT_TIMESTAMP)\ngroup by corporation_name, Month(date);"
    }
   ]
  },
  {
   "title": "Corp Tax Income - Current Month",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\ncorporation_name as \"Corporation\", sum(tax) as \"Amount\"\nFROM \n  corptools_corporationwalletjournalentry as wallet\nINNER JOIN eveonline_evecorporationinfo on eveonline_evecorporationinfo.corporation_id=tax_receiver_id\nWHERE \n  ref_type = \"bounty_prizes\" AND MONTH(date) = MONTH(CURRENT_TIMESTAMP)\ngroup by tax_receiver_id, Month(date);"
    }
   ]
  },
  {
   "title": "Corp Tax Income (All) - Selected Time Frame",
   "type": "table",
   "gridPos": { "h": 23, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\ncorporation_name as \"Corporation\", SUM(amount) AS \"Amount\"\nFROM \n  corptools_corporationwalletjournalentry as wallet\nINNER JOIN eveonline_evecharacter on eveonline_evecharacter.character_id=second_party_id\nWHERE \n  ref_type = \"agent_mission_reward\" OR ref_type = \"bounty_prizes\" OR ref_type = \"ess_escrow_transfer\" OR ref_type = \"corporate_reward_payout\" AND $__timeFilter(date)\ngroup by corporation_name;"
    }
   ]
  },
  {
   "title": "Corp Tax Income (ESS) - Current Month",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\ncorporation_name as \"Corporation\", SUM(amount) AS \"Amount\"\nFROM \n  corptools_corporationwalletjournalentry as wallet\nINNER JOIN eveonline_evecharacter on eveonline_evecharacter.character_id=second_party_id\nWHERE \n  ref_type = \"ess_escrow_transfer\" AND MONTH(date) = MONTH(CURRENT_TIMESTAMP)\ngroup by corporation_name, Month(date);"
    }
   ]
  },
  {
   "title": "Corp Tax Income (All) - Current Month",
   "type": "table",
   "gridPos": { "h": 23, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\ncorporation_name as \"Corporation\", SUM(amount) AS \"Amount\"\nFROM \n  corptools_corporationwalletjournalentry as wallet\nINNER JOIN eveonline_evecharacter on eveonline_evecharacter.character_id=second_party_id\nWHERE \n  ref_type = \"agent_mission_reward\" OR ref_type = \"bounty_prizes\" OR ref_type = \"ess_escrow_transfer\" OR ref_type = \"corporate_reward_payout\" AND MONTH(date) = MONTH(CURRENT_TIMESTAMP)\ngroup by corporation_name"
    }
   ]
  }
 ]
}