{
 "title": "SRP",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Total SRP Requests",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  post_time AS \"time\",\n  srp_ship_name AS metric,\n  count(id) AS \"id\"\nFROM srp_srpuserrequest\nWHERE\n  $__timeFilter(post_time)\nGROUP BY srp_ship_name,2\nORDER BY 3 desc\n"
    }
   ]
  },
  {
   "title": "Total SRP Cost",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  post_time AS \"time\",\n  srp_ship_name AS metric,\n  sum(srp_total_amount) AS \"id\"\nFROM srp_srpuserrequest\nWHERE\n  $__timeFilter(post_time)\nGROUP BY srp_ship_name,2\nORDER BY 3 desc"
    }
   ]
  },
  {
   "title": "Average SRP Cost",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  post_time AS \"time\",\n  srp_ship_name AS metric,\n  avg(srp_total_amount) AS \"id\"\nFROM srp_srpuserrequest\nWHERE\n  $__timeFilter(post_time)\nGROUP BY srp_ship_name,2\nORDER BY 3 desc"
    }
   ]
  }
 ]
}