{
 "title": "Auth Tasks",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "CORE Tasks",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1m,0),\n  task AS metric,\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskcompleted\nWHERE\n  $__timeFilter(time)\nGROUP BY 1, task\nORDER BY $__timeGroup(time,1m,0),\"id\""
    }
   ]
  },
  {
   "title": "Fails",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,1m,0),\n  task AS metric,\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskfailed\nWHERE\n  $__timeFilter(time)\nGROUP BY 1,2\nORDER BY $__timeGroup(time,1m,0)"
    }
   ]
  },
  {
   "title": "Max Tasks Per 10min Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,10m),\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskcompleted\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,10m)"
    }
   ]
  },
  {
   "title": "Max Tasks Failed Per 10min Period",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  count(id) AS \"id\"\nFROM celeryanalytics_celerytaskfailed\nWHERE\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "VPS CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{alias=\"InitServer\"}[5s])) by (mode) * 100 / count(node_cpu_seconds_total{alias=\"InitServer\"}) by (mode) or sum(irate(node_cpu_seconds_total{alias=\"InitServer\"}[5m])) by (mode) * 100 / count(node_cpu_seconds_total{alias=\"InitServer\"}) by (mode)"
    }
   ]
  },
  {
   "title": "Database Sizes",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \n    table_name AS metric, \n    round(((data_length + index_length) / 1024 / 1024), 2) as \"value\"\nFROM information_schema.TABLES \nORDER BY (data_length + index_length) DESC;"
    }
   ]
  }
 ]
}