{
 "title": "Assets Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dreads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(assets.quantity)\nfrom\n    corptools_characterasset assets\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\nwhere\n  it.group_id = 485\ngroup by ig.name"
    }
   ]
  },
  {
   "title": "Rorquals",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(assets.quantity)\nfrom\n    corptools_characterasset assets\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\nwhere\n  it.group_id = 883\ngroup by ig.name"
    }
   ]
  },
  {
   "title": "FAXes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(assets.quantity)\nfrom\n    corptools_characterasset assets\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\nwhere\n  it.group_id = 1538\ngroup by ig.name"
    }
   ]
  },
  {
   "title": "Supers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(assets.quantity)\nfrom\n    corptools_characterasset assets\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\nwhere\n  it.group_id = 659\ngroup by ig.name"
    }
   ]
  },
  {
   "title": "Titans",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(assets.quantity)\nfrom\n    corptools_characterasset assets\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\nwhere\n  it.group_id = 30\ngroup by ig.name"
    }
   ]
  },
  {
   "title": "Carriers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(assets.quantity)\nfrom\n    corptools_characterasset assets\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\nwhere\n  it.group_id = 547\ngroup by ig.name"
    }
   ]
  },
  {
   "title": "Jump Freighters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(assets.quantity)\nfrom\n    corptools_characterasset assets\n    join corptools_eveitemtype it on assets.type_id = it.type_id\n    join corptools_eveitemgroup ig on it.group_id = ig.group_id\nwhere\n  it.group_id = 902\ngroup by ig.name"
    }
   ]
  }
 ]
}