{
 "title": "Buyback",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Value by selected time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(price) AS value\r\nFROM\r\n  alliance_auth.buybackprogram_contract\r\nWHERE\r\n  status = 'finished'\r\n  AND date_completed BETWEEN $__timeFrom() AND $__timeTo();\r\n"
    }
   ]
  },
  {
   "title": "Contracts done by selected time",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  price AS value,\r\n  date_completed AS time\r\nFROM\r\n  alliance_auth.buybackprogram_contract\r\nWHERE\r\n  status = 'finished'\r\n  AND date_completed BETWEEN $__timeFrom() AND $__timeTo()\r\nORDER BY\r\n  date_completed ASC\r\n"
    }
   ]
  },
  {
   "title": "Current Active Contracts  (Number of Contacts)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(price)\r\nFROM\r\n  alliance_auth.buybackprogram_contract\r\nWHERE\r\n  status = 'outstanding'\r\n  AND EXTRACT(MONTH FROM date_issued) = EXTRACT(MONTH FROM CURRENT_TIMESTAMP)\r\nORDER BY\r\n  date_issued ASC"
    }
   ]
  },
  {
   "title": "Best value contracts top 10",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  `buybackprogram_contract`.`price` AS value,\r\n  `buybackprogram_contract`.`date_completed` AS time\r\nFROM\r\n  `alliance_auth`.`buybackprogram_contract`\r\nWHERE\r\n  `buybackprogram_contract`.`status` = 'finished'\r\nORDER BY\r\n  `buybackprogram_contract`.`price` DESC\r\nLIMIT\r\n  10;\r\n"
    }
   ]
  },
  {
   "title": "Current Active Contracts (Total Value of Contracts)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COALESCE(SUM(price), 0) AS value\r\nFROM\r\n  alliance_auth.buybackprogram_contract\r\nWHERE\r\n  status = 'outstanding'\r\n  AND EXTRACT(MONTH FROM date_issued) = EXTRACT(MONTH FROM CURRENT_TIMESTAMP);\r\n"
    }
   ]
  },
  {
   "title": "Contracts done by selected time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "alliance_auth",
     "rawSql": "SELECT\r\n  COUNT(price)\r\nFROM\r\n  alliance_auth.buybackprogram_contract\r\nWHERE\r\n  status = 'finished'\r\nAND date_completed BETWEEN $__timeFrom() AND $__timeTo();\r\n"
    }
   ]
  },
  {
   "title": "Buyback current month by value a day",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 9 }
  },
  {
   "title": "Total isk this month",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\nSELECT\r\n  SUM(price) AS value\r\nFROM\r\n  alliance_auth.buybackprogram_contract\r\nWHERE\r\n  status = 'finished'\r\n  AND EXTRACT(MONTH FROM date_completed) = EXTRACT(MONTH FROM CURRENT_TIMESTAMP)\r\n"
    }
   ]
  },
  {
   "title": "Buyback wallet",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  `name`,\r\n  `balance`\r\nFROM\r\n  `alliance_auth`.`corptools_corporationwalletdivision`\r\nWHERE\r\n  `id` = 5\r\n"
    }
   ]
  },
  {
   "title": "Total volume m3 this month",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(volume) AS value\r\nFROM\r\n  alliance_auth.buybackprogram_contract\r\nWHERE\r\n  status = 'finished'\r\n  AND EXTRACT(MONTH FROM date_completed) = EXTRACT(MONTH FROM CURRENT_TIMESTAMP)\r\n"
    }
   ]
  },
  {
   "title": "Volume a day",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  volume AS value,\r\n  date_completed AS time\r\nFROM\r\n  alliance_auth.buybackprogram_contract\r\nWHERE\r\n  status = 'finished'\r\n  AND EXTRACT(MONTH FROM date_completed) = EXTRACT(MONTH FROM CURRENT_TIMESTAMP)\r\nLIMIT\r\n 200;"
    }
   ]
  },
  {
   "title": "Volume by selected time total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(volume) AS value\r\nFROM\r\n  alliance_auth.buybackprogram_contract\r\nWHERE\r\n  status = 'finished'\r\n  AND date_completed BETWEEN $__timeFrom() AND $__timeTo();\r\n"
    }
   ]
  },
  {
   "title": "Contracts done this month",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  COUNT(price)\r\nFROM\r\n  alliance_auth.buybackprogram_contract\r\nWHERE\r\n  status = 'finished'\r\n  AND EXTRACT(MONTH FROM date_completed) = EXTRACT(MONTH FROM CURRENT_TIMESTAMP)\r\nORDER BY\r\n  date_completed ASC\r\n"
    }
   ]
  }
 ]
}